
REM Special version of the BUILD script to build hApps previously generated by the hc scaffolding tool (why paths are hard coded).

SET DnaName=oasis

@ECHO OFF
ECHO.
ECHO *********************************************************
ECHO NextGen Software Holochain hApp (Scaffolded) Builder v1.0
ECHO *********************************************************
ECHO.
ECHO Building hApp...
ECHO Compiling Zomes...
cargo build --release --target wasm32-unknown-unknown

ECHO Packing DNA...
hc dna pack dnas/%DnaName%/workdir
IF %ERRORLEVEL% NEQ 0 (Echo Error building the hApp &Exit /b 1)

ECHO Packing HAPP...
hc app pack workdir
IF %ERRORLEVEL% NEQ 0 (Echo Please update the correct path for the DNA in the happ.yaml found in the happ folder in %workdir%. Error building the hApp &Exit /b 1)

ECHO Cleaning Sandbox...
hc sandbox clean
ECHO.
ECHO hApp Built Successfully. 
ECHO.
pause
ECHO.
ECHO Running hApp...
ECHO.
hc sandbox generate workdir --run=8888 

