[package]
name = "oasis"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
name = "oasis"

[dependencies]
hdk = { workspace = true }

serde = { workspace = true }
serde_json = { workspace = true }

oasis_integrity = { workspace = true } 

[dev-dependencies]
holochain = { version = "=0.7.0", default-features = false, features = ["sweettest", "wasmer-wasmi"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
