[package]
name = "oasis"
version = "0.0.1"
authors = [ "davidellams", "david@nextgensoftware..co.uk" ]
edition = "2018"

[lib]
name = "oasis"
crate-type = [ "cdylib", "rlib" ]

[dependencies]
hdk = "0.0.140"
serde = "1"
