[package]
name = "holonet_api"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
name = "holonet_api"

[dependencies]
hdk = { workspace = true }

serde = { workspace = true }

holonet_api_integrity = { workspace = true } 
