name: "test"
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push: 
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  testbuild:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install nix
        uses: DeterminateSystems/nix-installer-action@v17

      - uses: cachix/cachix-action@v16
        with:
          name: holochain-ci

      - name: Install and test
        run: |
          nix develop . --command bash -lc "npm ci && npm test"

